nameOverride: notification-service

# Value of tag will be overridden by GitHub Actions when the docker image is built
image:
  repository: techxus/notification-service
  tag: "9153581f508a8acf4cc65eedcb01a34fff2763cf"

spring:
  profile: local

probes:
  readinessPath: /api/v1/notification/actuator/health/readiness
  livenessPath: /api/v1/notification/actuator/health/liveness
