nameOverride: notification-service

# Value of tag will be overridden by GitHub Actions when the docker image is built
image:
  repository: techxus/notification-service
  tag: "b4ebe10629727e8b75d3b383d9484b8e7c21b5b9"

spring:
  profile: local

probes:
  readinessPath: /api/v1/notification/actuator/health/readiness
  livenessPath: /api/v1/notification/actuator/health/liveness
