nameOverride: user-service

# Value of tag will be overridden by GitHub Actions when the docker image is built
image:
  repository: techxus/user-service
  tag: "9c764d42ec25a2647006d0e42a90898c949d88de"

spring:
  profile: local

probes:
  readinessPath: /api/v1/user/actuator/health/readiness
  livenessPath: /api/v1/user/actuator/health/liveness

