nameOverride: user-service

# Value of tag will be overridden by GitHub Actions when the docker image is built
image:
  repository: techxus/user-service
  tag: "d7733d7a4c4a3517726320f69c34006631ea4eef"

spring:
  profile: local

probes:
  readinessPath: /api/v1/user/actuator/health/readiness
  livenessPath: /api/v1/user/actuator/health/liveness

