nameOverride: user-service

# Value of tag will be overridden by GitHub Actions when the docker image is built
image:
  repository: techxus/user-service
  tag: "19baf21fa33c3aa098cf7294ef48e5ce65147ddd"

spring:
  profile: local

probes:
  readinessPath: /api/v1/user/actuator/health/readiness
  livenessPath: /api/v1/user/actuator/health/liveness

