nameOverride: user-service

# Value of tag will be overridden by GitHub Actions when the docker image is built
image:
  repository: techxus/user-service
  tag: "22b298dfeadd99072d04de724e666b0f52a5faad"

spring:
  profile: local

probes:
  readinessPath: /api/v1/user/actuator/health/readiness
  livenessPath: /api/v1/user/actuator/health/liveness

