nameOverride: user-service

# Value of tag will be overridden by GitHub Actions when the docker image is built
image:
  repository: techxus/user-service
  tag: "409157fe33e5afdb644e7dfbe5a3a361a8abe438"

spring:
  profile: local

probes:
  readinessPath: /api/v1/user/actuator/health/readiness
  livenessPath: /api/v1/user/actuator/health/liveness

