nameOverride: ""
fullnameOverride: ""

replicaCount: 1

spring:
  profile: ""
  defaultSchema: ""

image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

serviceAccount:
  create: false
  name: db-secrets-sa
  roleArn: arn:aws:iam::121897425968:role/ibank-eks-dev-db-secrets-reader

podAnnotations: {}

env: []

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts:
    - paths:
        - path: /
          pathType: Prefix

probes:
  enabled: true

  # Defaults assume NO servlet context-path.
  # Each service should override these if it sets server.servlet.context-path.
  readinessPath: /actuator/health/readiness
  livenessPath: /actuator/health/liveness
  startupPath: /actuator/health/liveness

  timeoutSeconds: 2

  startupFailureThreshold: 60
  startupPeriodSeconds: 5

  readinessInitialDelaySeconds: 5
  readinessPeriodSeconds: 10
  readinessFailureThreshold: 3

  livenessInitialDelaySeconds: 60
  livenessPeriodSeconds: 20
  livenessFailureThreshold: 6

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

config:
  enabled: false
  applicationYaml: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

monitoring:
  serviceMonitor:
    enabled: true
    releaseLabel: kps
    portName: http
    path: /actuator/prometheus
    interval: 30s

secretsStore:
  enabled: false
  region: us-east-1

  mountPath: "/mnt/secrets-store"
  mountPathPostgres: "/mnt/secrets-store/postgres"
  mountPathRedis: "/mnt/secrets-store/redis"
  mountPathMsk: "/mnt/secrets-store/msk"

  postgresSecretProviderClass: "ibank-postgres"
  redisSecretProviderClass: "ibank-redis"
  mskSecretProviderClass: "ibank-msk"

  datasourceUrl: ""
  secretArn: ""
