apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-service-config
data:
  application-k8s.yaml: |
    spring:
      cloud:
        gateway:
          routes:
            - id: user-service
              uri: http://user-service
              predicates:
                - Path=/api/v1/user/**

            - id: notification-service
              uri: http://notification-service
              predicates:
                - Path=/api/v1/notification/**
