nameOverride: reporting-service

# Value of tag will be overridden by GitHub Actions when the docker image is built
image:
  repository: techxus/reporting-service
  tag: "9b0e371f333c775c58532724a1ce5b7ccdddfa4e"

spring:
  profile: dev
  defaultSchema: reporting

probes:
  readinessPath: /api/v1/reporting/actuator/health/readiness
  livenessPath: /api/v1/reporting/actuator/health/liveness

monitoring:
  serviceMonitor:
    enabled: false

secretsStore:
  enabled: true
  region: us-east-1
  secretProviderClass: ibank-postgres
  secretArn: arn:aws:secretsmanager:us-east-1:121897425968:secret:ibank-eks-dev/rds/postgres-HnfeI8
  datasourceUrl: "jdbc:postgresql://ibank-eks-dev-postgres.c9jlnhhcva7f.us-east-1.rds.amazonaws.com:5432/appdb"
