nameOverride: reporting-service

# Value of tag will be overridden by GitHub Actions when the docker image is built
image:
  repository: techxus/reporting-service
  tag: "666e1e7e344d6e3d8a0a8fe28282b370bd0e3e4d"

spring:
  profile: dev
  defaultSchema: report

probes:
  enabled: true
  readinessPath: /api/v1/report/actuator/health/readiness
  livenessPath: /api/v1/report/actuator/health/liveness
  startupPath: /api/v1/report/actuator/health/liveness

monitoring:
  serviceMonitor:
    enabled: false

secretsStore:
  enabled: true
  region: us-east-1
  secretProviderClass: ibank-postgres
  secretArn: arn:aws:secretsmanager:us-east-1:121897425968:secret:ibank-eks-dev/rds/postgres-HnfeI8
  datasourceUrl: "jdbc:postgresql://ibank-eks-dev-postgres.c9jlnhhcva7f.us-east-1.rds.amazonaws.com:5432/appdb"
