apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - applicationsets/ibank-services-aws.yaml
  - applicationsets/ibank-services-local.yaml

  - apps/db-secrets-reader-sa.yaml
  - apps/ibank-postgres-spc.yaml

  - apps/secrets-store-csi-driver-app.yaml
  - apps/secrets-store-csi-aws-provider-app.yaml
