{{- if and .Values.config.enabled .Values.config.applicationYaml }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ default .Release.Name .Values.nameOverride }}-config
data:
  application.yaml: |
{{ .Values.config.applicationYaml | indent 4 }}
{{- end }}
