{{- if .Values.secretsStore.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretsStore.secretProviderClass | default "ibank-postgres" | quote }}
  namespace: {{ .Release.Namespace }}
spec:
  provider: aws
  parameters:
    region: {{ .Values.secretsStore.region | default "us-east-1" | quote }}
    objects: |
      - objectName: {{ .Values.secretsStore.secretArn | quote }}
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: "spring.datasource.username"
          - path: "password"
            objectAlias: "spring.datasource.password"
{{- end }}
