{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ default .Release.Name .Values.nameOverride }}
  namespace: {{ .Release.Namespace }}
  labels:
    release: kps
spec:
  selector:
    matchLabels:
      app: {{ default .Release.Name .Values.nameOverride }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: http
      path: {{ .Values.monitoring.serviceMonitor.path | default "/actuator/prometheus" }}
      interval: {{ .Values.monitoring.serviceMonitor.interval | default "30s" }}
{{- end }}
