apiVersion: v1
kind: Service
metadata:
  name: {{ default .Release.Name .Values.nameOverride }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ default .Release.Name .Values.nameOverride }}
    app.kubernetes.io/name: {{ default .Release.Name .Values.nameOverride }}
    app.kubernetes.io/instance: {{ .Release.Name }}

  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
